menu:
    Blog: /
    GitHub: https://github.com/alicefrancener
    Archive: archives/
    Tags: tags/

favicon: favicon.png
logo: favicon.png

# Comment
disqus:

# Analytics
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2019

# Image Credits
enable_image_credit: true 
